logging:
  level:
    root: INFO
server:
  port : 8081
  servlet:
    context-path: /api
spring:
  profiles:
    active: "dev"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
---
spring:
  profiles: "pro"
---
spring:
  profiles: "dev"
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: s3cr37l4b5c0urr13r
    driverClassName: org.postgresql.Driver
springdoc:
  paths-to-match: /**
spring-doc:
  swagger-ui:
    path: /swagger-ui.html